### ISSUE TITLE
Is this compatible with qtpass?

### ISSUE THREAD

**Issue by MountainX** [congma/pass-genphrase#4]
I am using qtpass 1.3.2-2 (x86_64)
https://www.archlinux.org/packages/community/x86_64/qtpass/

I would like to use this extension with it, but after a simple installation of pass-genphrase, qtpass did not use it for password generation. Is there a config option?

**Comment by congma** [comment]
Hello @MountainX, thanks for your interest. Because I haven't used qtpass before, I briefly read about it, but I didn't find in the documentation about supporting "pass extensions". It seems qtpass uses _an_ extension for the OTP feature, but I don't know if qtpass supports arbitrary pass extensions (I guess probably not).

If qtpass bypasses the usual way `pass` locates and executes "pass extensions", a newly installed extension like this one is unlikely to be understood by qtpass. In fact, this extension creates a separate "sub-command" namely `pass genphrase`, which isn't part of the original `pass` interface. For this reason I highly doubt if qtpass or any other external GUI could automatically use it.

**Comment by congma** [comment]
Hello @MountainX, I would like to close this issue because I'm not able to see an easy way for this extension to work with qtpass or other similar frontends for now. Nevertheless I think the question was a great one, namely how extensions and frontends may operate with each other. Please feel free to raise additional issues any time.
